{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-moshpit
  version: {{ version }}

source:
  path: ../..

build:
  script: |
    make VERBOSE=1
    make install    

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - altair
    - hmmer
    - matplotlib
    - metabat2
    - numpy
    - prodigal
    - pysam
    - samtools
    - qiime2 {{ release }}.*
    - q2-types-genomics {{ release }}.*
    - q2templates {{ release }}.*

test:
  imports:
    - q2_moshpit
    - qiime2.plugins.moshpit

about:
  home: https://github.com/bokulich-lab/q2-moshpit
  license: BSD-3-Clause
  license_family: BSD
