name: Test and build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: install dependencies
      run: python -m pip install --upgrade pip

    - name: lint
      run: |
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip
        q2lint
        pip install -q flake8
        flake8

  coverage:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: q2-shotgun-test
        mamba-version: "*"
        channels: conda-forge
    - name: Run tests with coverage
      run: |
        mamba install -c https://packages.qiime2.org/qiime2/2022.4/tested -c conda-forge -c bioconda -c defaults -y --file requirements.txt
        # https://github.com/merenlab/anvio/issues/1479
        # force remove does not work with mamba
        conda uninstall -y --force samtools
        mamba install -y -c bioconda samtools
        make dev
        qiime dev refresh-cache
        make test-cov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true

  build-and-test:
    needs: coverage
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        # necessary for versioneer
        fetch-depth: 0

    - name: Update missing libs
      if: matrix.os == 'macos-latest'
      run: |
        brew install gsl
        ln -s $HOME/homebrew/Cellar/gsl/2.7.1/lib/libgsl.27.dylib  /usr/local/lib/libgsl.0.dylib
        if [[ ! -f /usr/local/lib/libgslcblas.0.dylib ]]; then ln -s $HOME/homebrew/Cellar/gsl/2.7.1/lib/libgslcblas.0.dylib  /usr/local/lib/libgslcblas.0.dylib; fi

    # TODO: update this to @v1 when it lands
    - uses: qiime2/action-library-packaging@alpha1
      with:
        package-name: q2-moshpit
        additional-tests: pytest --pyargs q2_moshpit
        build-target: dev
        library-token: ${{ secrets.LIBRARY_TOKEN }}
