name: Upload coverage report

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find associated PR
        id: pr
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const response = await github.rest.search.issuesAndPullRequests({
              q: 'repo:${{ github.repository }} is:pr sha:${{ github.event.workflow_run.head_sha }}',
              per_page: 1,
            })
            const items = response.data.items
            if (items.length < 1) {
              console.error('No PRs found')
              return
            }
            const pullRequestNumber = items[0].number
            console.info("Pull request number is", pullRequestNumber)
            return pullRequestNumber

      - uses: codecov/codecov-action@v4
        name: Upload coverage report
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          override_pr: ${{ steps.pr.outputs.result }}
          override_commit: ${{ github.event.workflow_run.head_sha }}
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
